INSERT INTO heroes (id, name, strength, default_spawn_amount, power1, power2, rarity) VALUES
('troll', 'Troll', 7, 2, 'fight_monster', 'change_monster', 'Uncommon'),
('esprit', 'Esprit Sylvestre', 6, 2, 'fight_player_with_discarded_card', 'add_strength_to_challenger', 'Uncommon'),
('barde', 'Barde', 2, 1, 'shuffle_heroes_deck', 'change_hero', 'Rare'),
('elf', 'Elf', 8, 2, 'exchange_gems_with_player', 'exchange_2coins_for_life', 'Uncommon'),
('nain', 'Nain', 5, 2, 'gain_2gems', 'gain_life', 'Uncommon'),
('mage', 'Mage', 9, 2, 'see_player_card', 'remove_coin', 'Uncommon'),
('exorciste', 'Exorciste', 3, 4, 'shoot_player', 'all_in', 'Common'),
('gobelin', 'Gobelin', 4, 2, 'steal_gem', 'steal_gem', 'Uncommon'),
('geant', 'Giant', 10, 1, 'keep_gems', 'parry_this_you_f_casual', 'Rare'),
('chevalier', 'Chevalier', 11, 1, 'teamwork', 'steal_coin', 'Rare'),
('shapeshifter', 'Shapeshifter', 1, 1, 'mimic_hero', 'mimic_power', 'Rare'),
('werewolf', 'Werewolf', 0, 2, 'alternate_strength', 'dual_attack', 'Uncommon'),
('witch', 'Witch', 8, 1, 'blind_draw', 'force_transform', 'Rare'),
('prince', 'Mad Prince', 13, 1, 'tribute', 'execution', 'Rare'),
('queen', 'Mad Queen', 9, 1, 'royal_immunity', 'command_the_dead', 'Rare')
ON CONFLICT (id) DO NOTHING;

INSERT INTO monsters (id, name, strength, loot_coins, loot_gems, rarity, spawn_weight) VALUES
('skeleton', 'Skeleton', 5, 1, 1, 'common', 495),
('goblin_warrior', 'Goblin Warrior', 5, 1, 1, 'common', 495),
('wyvern', 'Wyvern', 6, 1, 2, 'common', 495),
('minotaur', 'Minotaur', 6, 1, 2, 'common', 495),
('spectre', 'Spectre', 7, 1, 3, 'uncommon', 300),
('basilisk', 'Basilisk', 7, 1, 3, 'uncommon', 300),
('golem', 'Stone Golem', 8, 1, 3, 'uncommon', 300),
('griffon', 'Griffon', 8, 1, 4, 'uncommon', 300),
('banshee', 'Banshee', 7, 1, 4, 'uncommon', 300),
('dragon', 'Ancient Dragon', 9, 1, 5, 'rare', 150),
('chimera', 'Chimera', 9, 1, 5, 'rare', 150),
('lich', 'Lich King', 10, 1, 6, 'rare', 150),
('frost_giant', 'Frost Giant', 10, 1, 5, 'rare', 150),
('phoenix', 'Eternal Phoenix', 11, 2, 6, 'legendary', 50),
('hydra', 'Nine-Headed Hydra', 12, 2, 7, 'legendary', 50),
('kraken', 'Abyssal Kraken', 13, 2, 8, 'legendary', 50),
('leviathan', 'Primordial Leviathan', 14, 3, 10, 'legendary', 50),
('ghost_king', 'Ghost of the King', 15, 4, 15, 'mythic', 5)
ON CONFLICT (id) DO NOTHING;

INSERT INTO powers (name, cost_gems, target_type, is_passive, trigger_event, description) VALUES
('change_monster', 0, 'monster', false, NULL, 'Swap one active monster with top card of monster deck'),
('fight_monster', 1, 'monster', false, NULL, 'Grants a free fight against a monster'),
('fight_player_with_discarded_card', 0, 'other_player', false, NULL, 'Initiate strength duel using a hero from discard pile'),
('add_strength_to_challenger', 2, 'session', false, NULL, 'Add +1 strength during same-turn fight_player_with_discarded_card'),
('shuffle_heroes_deck', 0, 'session', false, NULL, 'Return all non-burned discarded heroes to deck and shuffle'),
('change_hero', 2, 'self', false, NULL, 'Draw a new hero card and discard your current one'),
('exchange_gems_with_player', 0, 'other_player', false, NULL, 'Swap your gems with those of a target player'),
('exchange_2coins_for_life', 0, 'self', false, NULL, 'Spend 2 coins to gain 1 life'),
('gain_2gems', 0, 'self', false, NULL, 'Instantly gain 2 gems'),
('gain_life', 6, 'self', false, NULL, 'Instantly gain 1 life'),
('see_player_card', 0, 'other_player', false, NULL, 'Secretly view another player''s current hero card'),
('remove_coin', 3, 'other_player', false, NULL, 'Force target player to lose 1 coin'),
('shoot_player', 0, 'other_player', false, NULL, 'Guess target''s hero; if correct, they lose 1 life'),
('all_in', 69, 'self', false, NULL, 'If last shoot_player correct: double gems; if wrong: lose all gems'),
('steal_gem', 0, 'other_player', false, NULL, 'Steal one gem from a target player'),
('parry_this_you_f_casual', 6, 'other_player', false, NULL, 'Reduce target player''s life by 1'),
('steal_coin', 5, 'other_player', false, NULL, 'Steal 1 coin from a target player'),
('mimic_power', 6, 'other_player', false, NULL, 'Copy and execute order-0 active power of target''s hero'),
('mimic_hero', 0, 'other_player', false, NULL, 'Copy another player''s hero abilities temporarily'),
('dual_attack', 6, 'session', false, NULL, 'After first monster fight, immediately fight next active monster'),
('blind_draw', 0, 'other_player', false, NULL, 'Draw a card blindly from the deck'),
('force_transform', 4, 'other_player', false, NULL, 'Force target to discard hero and draw new one'),
('execution', 6, 'session', false, NULL, 'Burn a hero card from the game'),
('command_the_dead', 4, 'monster', false, NULL, 'Use discarded hero to fight monster and gain loot'),
('keep_gems', 0, 'self', true, 'steal_attempt', 'Cancels steal attempts against you'),
('teamwork', 0, 'self', true, 'gems_gained', 'When you gain gems, duplicate the amount'),
('alternate_strength', 0, 'self', true, 'turn_start', 'Strength alternates between 5 and 12 each turn'),
('tribute', 0, 'self', true, 'gems_gained', 'When another player gains gems, half are given to you'),
('royal_immunity', 0, 'self', true, 'always', 'Cannot be targeted by player attacks; no loot from direct monster fights')
ON CONFLICT (name) DO NOTHING;
