package design

import (
	"fmt"

	"no-heroes-no-lies/internal/models"
)

var cardsByID map[string]models.Card
var powersByID map[string]models.Power

func init() {
	initCards()
	initPowers()
}

func initCards() {
	cardsByID = map[string]models.Card{
		// Heroes (15)
		"troll": {
			ID:                      "troll",
			Type:                    "hero",
			Name:                    "Troll",
			Description:             "Combat specialist",
			Strength:                7,
			PowerIDs:                []string{"change_monster", "fight_monster"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 2,
			CoverURL:                "",
		},
		"esprit": {
			ID:                      "esprit",
			Type:                    "hero",
			Name:                    "Esprit Sylvestre",
			Description:             "PvP fighter",
			Strength:                6,
			PowerIDs:                []string{"fight_player_with_discarded_card", "add_strength_to_challenger"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 2,
			CoverURL:                "",
		},
		"barde": {
			ID:                      "barde",
			Type:                    "hero",
			Name:                    "Barde",
			Description:             "Deck manipulation",
			Strength:                2,
			PowerIDs:                []string{"shuffle_heroes_deck", "change_hero"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"elf": {
			ID:                      "elf",
			Type:                    "hero",
			Name:                    "Elf",
			Description:             "Resource trading",
			Strength:                8,
			PowerIDs:                []string{"exchange_gems_with_player", "exchange_2coins_for_life"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 2,
			CoverURL:                "",
		},
		"nain": {
			ID:                      "nain",
			Type:                    "hero",
			Name:                    "Nain",
			Description:             "Resource generation",
			Strength:                5,
			PowerIDs:                []string{"gain_2gems", "gain_life"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 2,
			CoverURL:                "",
		},
		"mage": {
			ID:                      "mage",
			Type:                    "hero",
			Name:                    "Mage",
			Description:             "Information & disruption",
			Strength:                9,
			PowerIDs:                []string{"see_player_card", "remove_coin"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 2,
			CoverURL:                "",
		},
		"exorciste": {
			ID:                      "exorciste",
			Type:                    "hero",
			Name:                    "Exorciste",
			Description:             "High risk/reward",
			Strength:                3,
			PowerIDs:                []string{"shoot_player", "all_in"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 4,
			CoverURL:                "",
		},
		"gobelin": {
			ID:                      "gobelin",
			Type:                    "hero",
			Name:                    "Gobelin",
			Description:             "Gem thief (dual steal)",
			Strength:                4,
			PowerIDs:                []string{"steal_gem", "steal_gem"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 2,
			CoverURL:                "",
		},
		"geant": {
			ID:                      "geant",
			Type:                    "hero",
			Name:                    "Geant",
			Description:             "Tank with damage",
			Strength:                10,
			PowerIDs:                []string{"keep_gems", "parry_this_you_f_casual"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"chevalier": {
			ID:                      "chevalier",
			Type:                    "hero",
			Name:                    "Chevalier",
			Description:             "Elite knight",
			Strength:                11,
			PowerIDs:                []string{"teamwork", "steal_coin"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"shapeshifter": {
			ID:                      "shapeshifter",
			Type:                    "hero",
			Name:                    "Shapeshifter",
			Description:             "Copycat abilities",
			Strength:                1,
			PowerIDs:                []string{"mimic_hero", "mimic_power"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"werewolf": {
			ID:                      "werewolf",
			Type:                    "hero",
			Name:                    "Werewolf",
			Description:             "Alternates 5/12",
			Strength:                0,
			PowerIDs:                []string{"alternate_strength", "dual_attack"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 2,
			CoverURL:                "",
		},
		"witch": {
			ID:                      "witch",
			Type:                    "hero",
			Name:                    "Witch",
			Description:             "Transformation magic",
			Strength:                8,
			PowerIDs:                []string{"blind_draw", "force_transform"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"prince": {
			ID:                      "prince",
			Type:                    "hero",
			Name:                    "Mad Prince",
			Description:             "Strongest hero",
			Strength:                13,
			PowerIDs:                []string{"tribute", "execution"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"queen": {
			ID:                      "queen",
			Type:                    "hero",
			Name:                    "Mad Queen",
			Description:             "Immune to attacks",
			Strength:                9,
			PowerIDs:                []string{"royal_immunity", "command_the_dead"},
			Loot:                    models.Loot{},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},

		// Monsters (18)
		"skeleton": {
			ID:          "skeleton",
			Type:        "monster",
			Name:        "Skeleton",
			Description: "",
			Strength:    5,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  1,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"goblin_warrior": {
			ID:          "goblin_warrior",
			Type:        "monster",
			Name:        "Goblin Warrior",
			Description: "",
			Strength:    5,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  1,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"wyvern": {
			ID:          "wyvern",
			Type:        "monster",
			Name:        "Wyvern",
			Description: "",
			Strength:    6,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  2,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"minotaur": {
			ID:          "minotaur",
			Type:        "monster",
			Name:        "Minotaur",
			Description: "",
			Strength:    6,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  2,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"spectre": {
			ID:          "spectre",
			Type:        "monster",
			Name:        "Spectre",
			Description: "",
			Strength:    7,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  3,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"basilisk": {
			ID:          "basilisk",
			Type:        "monster",
			Name:        "Basilisk",
			Description: "",
			Strength:    7,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  3,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"golem": {
			ID:          "golem",
			Type:        "monster",
			Name:        "Stone Golem",
			Description: "",
			Strength:    8,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  3,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"griffon": {
			ID:          "griffon",
			Type:        "monster",
			Name:        "Griffon",
			Description: "",
			Strength:    8,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  4,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"banshee": {
			ID:          "banshee",
			Type:        "monster",
			Name:        "Banshee",
			Description: "",
			Strength:    7,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  4,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"dragon": {
			ID:          "dragon",
			Type:        "monster",
			Name:        "Ancient Dragon",
			Description: "",
			Strength:    9,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  5,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"chimera": {
			ID:          "chimera",
			Type:        "monster",
			Name:        "Chimera",
			Description: "",
			Strength:    9,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  5,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"lich": {
			ID:          "lich",
			Type:        "monster",
			Name:        "Lich King",
			Description: "",
			Strength:    10,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  6,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"frost_giant": {
			ID:          "frost_giant",
			Type:        "monster",
			Name:        "Frost Giant",
			Description: "",
			Strength:    10,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 1,
				Gems:  5,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"phoenix": {
			ID:          "phoenix",
			Type:        "monster",
			Name:        "Eternal Phoenix",
			Description: "",
			Strength:    11,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 2,
				Gems:  6,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"hydra": {
			ID:          "hydra",
			Type:        "monster",
			Name:        "Nine-Headed Hydra",
			Description: "",
			Strength:    12,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 2,
				Gems:  7,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"kraken": {
			ID:          "kraken",
			Type:        "monster",
			Name:        "Abyssal Kraken",
			Description: "",
			Strength:    13,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 2,
				Gems:  8,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"leviathan": {
			ID:          "leviathan",
			Type:        "monster",
			Name:        "Primordial Leviathan",
			Description: "",
			Strength:    14,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 3,
				Gems:  10,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
		"ghost_king": {
			ID:          "ghost_king",
			Type:        "monster",
			Name:        "Ghost of the King",
			Description: "",
			Strength:    15,
			PowerIDs:    nil,
			Loot: models.Loot{
				Coins: 4,
				Gems:  15,
			},
			DefaultAmountPerSession: 1,
			CoverURL:                "",
		},
	}
}

func initPowers() {
	powersByID = map[string]models.Power{
		// Active powers
		"change_monster": {
			ID:          "change_monster",
			Name:        "change_monster",
			Type:        "active",
			Cost:        0,
			Action:      "change_monster",
			Target:      "monster",
			Trigger:     "",
			Order:       0,
			Description: "Swap one active monster with top card of monster deck",
		},
		"fight_monster": {
			ID:          "fight_monster",
			Name:        "fight_monster",
			Type:        "active",
			Cost:        1,
			Action:      "fight_monster",
			Target:      "monster",
			Trigger:     "",
			Order:       0,
			Description: "Grants a free fight against a monster without normal restrictions",
		},
		"fight_player_with_discarded_card": {
			ID:          "fight_player_with_discarded_card",
			Name:        "fight_player_with_discarded_card",
			Type:        "active",
			Cost:        0,
			Action:      "fight_player_with_discarded_card",
			Target:      "other_player",
			Trigger:     "",
			Order:       0,
			Description: "Initiate strength duel using a hero from discard pile",
		},
		"add_strength_to_challenger": {
			ID:          "add_strength_to_challenger",
			Name:        "add_strength_to_challenger",
			Type:        "active",
			Cost:        2,
			Action:      "add_strength_to_challenger",
			Target:      "session",
			Trigger:     "",
			Order:       0,
			Description: "Add +1 strength during same-turn fight_player_with_discarded_card",
		},
		"shuffle_heroes_deck": {
			ID:          "shuffle_heroes_deck",
			Name:        "shuffle_heroes_deck",
			Type:        "active",
			Cost:        0,
			Action:      "shuffle_heroes_deck",
			Target:      "session",
			Trigger:     "",
			Order:       0,
			Description: "Return all non-burned discarded heroes to deck and shuffle",
		},
		"change_hero": {
			ID:          "change_hero",
			Name:        "change_hero",
			Type:        "active",
			Cost:        2,
			Action:      "change_hero",
			Target:      "self",
			Trigger:     "",
			Order:       0,
			Description: "Draw a new hero card and discard your current one",
		},
		"exchange_gems_with_player": {
			ID:          "exchange_gems_with_player",
			Name:        "exchange_gems_with_player",
			Type:        "active",
			Cost:        0,
			Action:      "exchange_gems_with_player",
			Target:      "other_player",
			Trigger:     "",
			Order:       0,
			Description: "Swap your gems with those of a target player",
		},
		"exchange_2coins_for_life": {
			ID:          "exchange_2coins_for_life",
			Name:        "exchange_2coins_for_life",
			Type:        "active",
			Cost:        0,
			Action:      "exchange_2coins_for_life",
			Target:      "self",
			Trigger:     "",
			Order:       0,
			Description: "Spend 2 coins to gain 1 life",
		},
		"gain_2gems": {
			ID:          "gain_2gems",
			Name:        "gain_2gems",
			Type:        "active",
			Cost:        0,
			Action:      "gain_2gems",
			Target:      "self",
			Trigger:     "",
			Order:       0,
			Description: "Instantly gain 2 gems",
		},
		"gain_life": {
			ID:          "gain_life",
			Name:        "gain_life",
			Type:        "active",
			Cost:        6,
			Action:      "gain_life",
			Target:      "self",
			Trigger:     "",
			Order:       0,
			Description: "Instantly gain 1 life",
		},
		"see_player_card": {
			ID:          "see_player_card",
			Name:        "see_player_card",
			Type:        "active",
			Cost:        0,
			Action:      "see_player_card",
			Target:      "other_player",
			Trigger:     "",
			Order:       0,
			Description: "Secretly view another player's current hero card",
		},
		"remove_coin": {
			ID:          "remove_coin",
			Name:        "remove_coin",
			Type:        "active",
			Cost:        3,
			Action:      "remove_coin",
			Target:      "other_player",
			Trigger:     "",
			Order:       0,
			Description: "Force target player to lose 1 coin (removed from game)",
		},
		"shoot_player": {
			ID:          "shoot_player",
			Name:        "shoot_player",
			Type:        "active",
			Cost:        0,
			Action:      "shoot_player",
			Target:      "other_player",
			Trigger:     "",
			Order:       0,
			Description: "Guess target's hero; if correct, they lose 1 life",
		},
		"all_in": {
			ID:          "all_in",
			Name:        "all_in",
			Type:        "active",
			Cost:        69,
			Action:      "all_in",
			Target:      "self",
			Trigger:     "",
			Order:       0,
			Description: "If last shoot_player correct: double gems; if wrong: lose all gems",
		},
		"steal_gem": {
			ID:          "steal_gem",
			Name:        "steal_gem",
			Type:        "active",
			Cost:        0,
			Action:      "steal_gem_0",
			Target:      "other_player",
			Trigger:     "",
			Order:       0,
			Description: "Steal one gem from a target player",
		},
		"parry_this_you_f_casual": {
			ID:          "parry_this_you_f_casual",
			Name:        "parry_this_you_f_casual",
			Type:        "active",
			Cost:        6,
			Action:      "parry_this_you_f_casual",
			Target:      "other_player",
			Trigger:     "",
			Order:       0,
			Description: "Reduce target player's life by 1",
		},
		"steal_coin": {
			ID:          "steal_coin",
			Name:        "steal_coin",
			Type:        "active",
			Cost:        5,
			Action:      "steal_coin",
			Target:      "other_player",
			Trigger:     "",
			Order:       0,
			Description: "Steal 1 coin from a target player",
		},
		"mimic_power": {
			ID:          "mimic_power",
			Name:        "mimic_power",
			Type:        "active",
			Cost:        6,
			Action:      "mimic_power",
			Target:      "other_player",
			Trigger:     "",
			Order:       0,
			Description: "Copy and execute order-0 active power of target's hero",
		},
		"mimic_hero": {
			ID:          "mimic_hero",
			Name:        "mimic_hero",
			Type:        "active",
			Cost:        0,
			Action:      "mimic_hero",
			Target:      "other_player",
			Trigger:     "",
			Order:       0,
			Description: "Copy another player's hero abilities temporarily",
		},
		"dual_attack": {
			ID:          "dual_attack",
			Name:        "dual_attack",
			Type:        "active",
			Cost:        6,
			Action:      "dual_attack",
			Target:      "session",
			Trigger:     "",
			Order:       0,
			Description: "After first monster fight, immediately fight next active monster",
		},
		"blind_draw": {
			ID:          "blind_draw",
			Name:        "blind_draw",
			Type:        "active",
			Cost:        0,
			Action:      "blind_draw",
			Target:      "other_player",
			Trigger:     "",
			Order:       0,
			Description: "Draw a card blindly from the deck",
		},
		"force_transform": {
			ID:          "force_transform",
			Name:        "force_transform",
			Type:        "active",
			Cost:        4,
			Action:      "force_transform",
			Target:      "other_player",
			Trigger:     "",
			Order:       0,
			Description: "Force target to discard hero and draw new one",
		},
		"execution": {
			ID:          "execution",
			Name:        "execution",
			Type:        "active",
			Cost:        6,
			Action:      "execution",
			Target:      "session",
			Trigger:     "",
			Order:       0,
			Description: "Burn (permanently remove) a hero card from the game",
		},
		"command_the_dead": {
			ID:          "command_the_dead",
			Name:        "command_the_dead",
			Type:        "active",
			Cost:        4,
			Action:      "command_the_dead",
			Target:      "monster",
			Trigger:     "",
			Order:       0,
			Description: "Use discarded hero to fight monster and gain loot",
		},

		// Passive powers
		"keep_gems": {
			ID:          "keep_gems",
			Name:        "keep_gems",
			Type:        "passive",
			Cost:        0,
			Action:      "keep_gems",
			Target:      "",
			Trigger:     "steal_attempt",
			Order:       0,
			Description: "Cancels steal attempts against you",
		},
		"teamwork": {
			ID:          "teamwork",
			Name:        "teamwork",
			Type:        "passive",
			Cost:        0,
			Action:      "teamwork",
			Target:      "",
			Trigger:     "gems_gained",
			Order:       0,
			Description: "When you gain gems, duplicate the amount (double gems)",
		},
		"alternate_strength": {
			ID:          "alternate_strength",
			Name:        "alternate_strength",
			Type:        "passive",
			Cost:        0,
			Action:      "alternate_strength",
			Target:      "",
			Trigger:     "turn_start",
			Order:       0,
			Description: "Strength alternates between 5 (human) and 12 (wolf) each turn",
		},
		"tribute": {
			ID:          "tribute",
			Name:        "tribute",
			Type:        "passive",
			Cost:        0,
			Action:      "tribute",
			Target:      "",
			Trigger:     "gems_gained",
			Order:       0,
			Description: "When another player gains gems, half are given to you instead",
		},
		"royal_immunity": {
			ID:          "royal_immunity",
			Name:        "royal_immunity",
			Type:        "passive",
			Cost:        0,
			Action:      "royal_immunity",
			Target:      "",
			Trigger:     "always",
			Order:       0,
			Description: "Cannot be targeted by player attacks; gets no loot from direct monster fights",
		},
	}
}

// GetCard returns the card definition for a given ID.
func GetCard(id string) (models.Card, error) {
	c, ok := cardsByID[id]
	if !ok {
		return models.Card{}, fmt.Errorf("unknown card id %q", id)
	}
	return c, nil
}

// GetPower returns the power definition for a given ID.
func GetPower(id string) (models.Power, error) {
	p, ok := powersByID[id]
	if !ok {
		return models.Power{}, fmt.Errorf("unknown power id %q", id)
	}
	return p, nil
}

// AllCards returns all card definitions (heroes + monsters).
func AllCards() []models.Card {
	out := make([]models.Card, 0, len(cardsByID))
	for _, c := range cardsByID {
		out = append(out, c)
	}
	return out
}

